I18next Frontend and Backend implementation
yalla-coop/cost-of-living-support pull request #100
Opened 2022-11-18 13:50 UTC by cemalokten

#### Issues this PR relates to #53

2022-11-24 12:51 UTC, RamyAlshurafa requested changes
- [ ] the app crashes when there is no language selected on the first run
- [ ] the flag icon should take a pointer cursor
- [ ] the whole language button should be clickable
- [ ] change common module folder to translations or i18n
- [ ] this should be right to left  `Feeling stressed or overwhelmed`
<img width="433" alt="image" src="https://user-images.githubusercontent.com/34629478/203788325-26108322-d674-40ac-ad72-098a02085b69.png">
- [ ] also it takes the wrong translation `Feeling stressed or overwhelmed` takes the `see advice` value, its may be the dummy data issue
- [ ] the accessibility button should be on the right side on desktop 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/34629478/203788913-79ff0f06-988f-441c-81ca-181effdc6bd2.png">

2022-11-24 17:38 UTC, cemalokten commented
@jema28 Is there a welsh flag SVG available in the same style as the other?

2022-11-24 18:01 UTC, cemalokten commented
-  Welsh flag doesn't appear on the select language page - **Asked @jema28 for SVG**
- there is a large scroll in the select language page - **It overlays the component below, so the lower component defines the height and scroll**
-  if i select Welsh, the Welsh word doesn't appear on the navbar - **Works for me, either 'Welsh' or 'CY'**
-  the accessibility button should be on the right side on desktop - **The navbar switches to the more compact design from tablet breakpoint**

2022-11-29 10:18 UTC, RamyAlshurafa approved these changes

2022-11-29 10:18 UTC, merged