Edit contact details
yalla-coop/cost-of-living-support pull request #102
Opened 2022-11-21 12:28 UTC by remaininlight

#### Issues this PR relates to
#38 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install
N/A
---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-22 08:57 UTC, fadeomar requested changes
hey @remaininlight nice work but I've some notes: 
  - [ ] the page title should be change to (Edit account details)
  - [ ] the tip card that says (Please note that changing your unique link will mean we need to review your profile again ) need to be added before the button https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A19083&t=da3LfZoEdwgaf199-0 
  - [ ] the space between the page title and the (Below you can edit details for your customers such as your adviser contact line) line should be 32px 
![image](https://user-images.githubusercontent.com/39485495/203269750-8d413e92-0f84-40a9-bac7-8d37e3a53869.png)

2022-11-22 08:57 UTC, fadeomar commented on client/src/pages/Admin/EditDetails/index.js
> +    async function setOrganisation() {
```suggestion
    function setOrganisation() {
```
no need for async keyword here since you didn't use await keyword inside the function

2022-11-22 16:27 UTC, remaininlight commented
Thanks @fadeomar! I've made the changes

2022-11-23 08:17 UTC, fadeomar approved these changes

2022-11-23 08:17 UTC, merged