add social banner
yalla-coop/cost-of-living-support pull request #104
Opened 2022-11-23 11:16 UTC by Israa91

#### Issues this PR relates to
#50 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-23 19:45 UTC, fadeomar requested changes
- [ ] "footer goes here"still appears on the pages 
![image](https://user-images.githubusercontent.com/39485495/203629750-23360c7b-05a6-49eb-9826-c9822b69764f.png)

 - [ ] copy icon should have "courser" pointer 
![image](https://user-images.githubusercontent.com/39485495/203630019-cd30d12d-a83c-44be-86b7-01202b0b23e3.png)

 - [x] the icons in share bare shows some blur on it because they are images not SVG's, please use SVG instead 
![image](https://user-images.githubusercontent.com/39485495/203631288-92055ece-7e58-4e91-92e0-5178174a18f0.png)

 - [ ] the space between the text and the icon not correct it's 16px but it suppose to be 8px because there is a 8px gap between the items and 8px right margin to the text  
![image](https://user-images.githubusercontent.com/39485495/203631171-ceec69d6-db5f-47d0-9b1c-e5fa198c5998.png)

 - [ ] clicking the facebook icon show an error in the facebook prompt "Parameter 'href' should represent a valid URL
"
![image](https://user-images.githubusercontent.com/39485495/203631573-1c3edf05-1348-4a1a-9588-42175f8d39f1.png)

 - [ ] clicking on WhatsApp icon open a prompt but show an error even when the WhatsApp client is open 
![image](https://user-images.githubusercontent.com/39485495/203632344-057d8163-3c13-4417-baea-f2afff77f9fe.png)

 - [ ] the title looks weird in the email because it's markdown you should put a text as a title not markdown 
![image](https://user-images.githubusercontent.com/39485495/203632673-491b01d2-9e3f-4b37-a476-a62127ddaef2.png)

2022-11-23 19:45 UTC, fadeomar commented on client/src/components/SocialBanner/index.js
> +      <Col w={[4, 12, 12]}>
you don't need the Grid item to wrap the share component because it's a single component at take all screen width

2022-11-23 19:45 UTC, fadeomar commented on client/src/components/SocialBanner/style.js
> +  width: 105%;
no need to increase the component width if it's in the correct position

2022-11-23 19:45 UTC, fadeomar commented on client/src/components/SocialBanner/style.js
> +  gap: 8px;
no need for gap because the text take 8px right margin

2022-11-24 13:56 UTC, Israa91 commented
Hey @fadeomar , this error Parameter 'href' should represent a valid URL ,because you are using localhost ,try use 127.0.01 instead ,see this link https://stackoverflow.com/questions/66097384/react-share-parameter-href-should-represent-a-valid-url

2022-11-27 14:01 UTC, fadeomar approved these changes

2022-11-28 14:31 UTC, merged