create organisations page and export
yalla-coop/cost-of-living-support pull request #105
Opened 2022-11-23 11:34 UTC by RamyAlshurafa

#### Issues this PR relates to
#27 #26 #12
 
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-23 14:41 UTC, fadeomar requested changes
nice work ramy:
  - [x] I've noticed the same modal description when changing between admin and super admin roles and I think it's not correct when changing the role from super admin to admin https://www.loom.com/share/9b84b886228340eb8f517861ba3cfb2e

2022-11-23 14:41 UTC, fadeomar commented on client/src/pages/Admin/Organisations/index.js
> +  signupDate,
it would be good to create UserRow.js file for UserRow component in separate file

2022-11-24 10:57 UTC, RamyAlshurafa commented on server/modules/csv/utils/csv-headers.js
> +  { label: 'type of organisation', value: 'type_of_organisation' },
done

2022-11-24 10:59 UTC, RamyAlshurafa commented on client/src/pages/Admin/Organisations/index.js
> +  signupDate,
done

2022-11-24 11:57 UTC, merged