Fix navigation direction and duplicate arrow
yalla-coop/cost-of-living-support pull request #162
Opened 2022-12-07 12:06 UTC by cemalokten

#### Issues this PR relates to #134 

closes #134

2022-12-08 11:55 UTC, RamyAlshurafa requested changes

2022-12-08 11:55 UTC, RamyAlshurafa commented on client/src/context/common.js
> -
why are you deleting this?!!

this is the code that changes the direction of the layout

2022-12-08 11:58 UTC, cemalokten commented on client/src/context/common.js
> -
Because it changes the direction of the entire site, the navigation bar requires a different layout for RTL, this method means that it doesn't meet the requirements of the design. The code that I have pushed works the same, but does not effect the nav-bar.

2022-12-12 08:08 UTC, RamyAlshurafa approved these changes

2022-12-12 08:08 UTC, merged