Language frontend
yalla-coop/cost-of-living-support pull request #77
Opened 2022-11-09 19:04 UTC by cemalokten

#### Issues this PR relates to #53

- This PR is for the Front end parts of the issue, currently no functionality.
- Developed inside storybook
- Flags and languages have not been added

=======

2022-11-10 14:54 UTC, fadeomar requested changes
hey @cemalokten 
  - [x] for icons file can please make sure that all props are in camelcase otherwise will throw errors  in console
  - [x] I'm able to run the code because you need to pull the latest develop branch with the new package json

2022-11-10 14:54 UTC, fadeomar commented on client/src/components/Icon/icons/AR.js
> +        clip-rule="evenodd"
should be camelCase fillRule the same for all svg props

2022-11-10 14:54 UTC, fadeomar commented on client/src/components/Icon/icons/AR.js
> +        clip-rule="evenodd"
should be camelCase fillRule the same for all svg props

2022-11-13 12:02 UTC, fadeomar requested changes
hey @cemalokten nice work: 
but there are some points that need to be fixed: 
  - [x] in the acceptability bar in Desktop https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5099%3A26554 there is no icon for (Increase text size) 
  wireframe:  ![image](https://user-images.githubusercontent.com/39485495/201520175-0388024e-722b-4ba6-b869-3e7da2c91ebe.png)
  storybook: 
![image](https://user-images.githubusercontent.com/39485495/201520241-bdffc8df-a1cf-4205-ad74-cd5baf3d5d7c.png)

  - [ ] also you can see the order is not correct
  storybook: 
![image](https://user-images.githubusercontent.com/39485495/201520294-e0e06984-b045-493c-b009-f7b3609678e8.png)
 wireframe: 
![image](https://user-images.githubusercontent.com/39485495/201520318-161e9066-3414-46ef-b978-0925650ce028.png)

  - [ ] the accessibility icon is not well exported (look to the man head ) 
  
![image](https://user-images.githubusercontent.com/39485495/201520415-0763b1c0-5c90-4353-af79-d8a03c73f35e.png)
![image](https://user-images.githubusercontent.com/39485495/201520443-0f020470-5906-4652-b7e9-c0be3358065b.png)

  - [ ] important point is to add the accessibility bar to the pages or layout not only the storybook

2022-11-14 13:00 UTC, fadeomar commented
hey @cemalokten to update you on this @ramy has fixed the general layout so you need only to add the accessibility bar in one place, pull the latest develop and you will see the change in the general layout 👍

2022-11-14 18:28 UTC, cemalokten commented
1 - This has been updated so the magnifying icon is on both desktop and mobile - see https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4601%3A23308&t=0DUpgJjY3dpNEo4S-0

2 - I've been following the order in the `Hyde Design System` file @jema28 which button order is correct?

![image](https://user-images.githubusercontent.com/60609268/201650563-579efdd7-4504-4dda-858c-c8b084fe862a.png)

2022-11-15 11:26 UTC, fadeomar approved these changes

2022-11-16 07:57 UTC, fadeomar requested changes

2022-11-16 07:57 UTC, fadeomar commented on client/src/components/Language/LanguageSelector/index.js
> +  am: 'Russian',
duplicate key 'am'

2022-11-18 16:44 UTC, cemalokten commented
@fadeomar Added missing flags and constants object for languages

2022-11-20 13:23 UTC, fadeomar approved these changes

2022-11-20 13:24 UTC, merged