create content pages
yalla-coop/cost-of-living-support pull request #90
Opened 2022-11-15 16:12 UTC by RamyAlshurafa

#### Issues this PR relates to

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-16 16:07 UTC, fadeomar requested changes
- [ ] in Private tenant>> Debt Advice Locator >> there is a helpful link for Debt Advice Locator not exists please check other subsections 
![image](https://user-images.githubusercontent.com/39485495/202218962-32fcd68d-a4b7-4691-83f0-cf28ede3223d.png)

  - [ ] the title in all sub routs says "the name of the sub route" Renter" not "tenant" 
![image](https://user-images.githubusercontent.com/39485495/202220883-6ec7f236-e42a-4bf9-9764-43edc6a54a81.png)

  - [ ] the header Colors are not correct for the sections renders the default colors in "paying my bills" should be Tertiary/Main not Secondary/Main
![image](https://user-images.githubusercontent.com/39485495/202221451-1cfcc831-54d6-4f08-9f9f-0d7e523f0141.png)

  - [ ] the Go back button doesn't exist on all content pages 
![image](https://user-images.githubusercontent.com/39485495/202222558-8c99ff81-1316-4349-96a9-8cf768dd25a6.png)

2022-11-16 16:12 UTC, fadeomar requested changes

2022-11-16 16:12 UTC, fadeomar commented on client/src/pages/OrgPublic/Section/useTopics.js
> +        // message.error('Something went wrong, please try again later');
handle the error

2022-11-16 16:12 UTC, fadeomar commented on client/src/pages/OrgPublic/Section/index.js
> +        // message.error('Something went wrong, please try again later');
handle the error

2022-11-17 05:05 UTC, RamyAlshurafa commented
>  the title in all sub routs says "the name of the sub route" Renter" not "tenant"

the content provided from Hyde is tenant which i think is the correct https://docs.google.com/spreadsheets/d/1UmIaGBR5KC9SD4KbweGL4OZVqFEtF7lB/edit#gid=978263828

2022-11-17 05:29 UTC, RamyAlshurafa commented on client/src/components/Cards/Tips/index.js
> +    ));
fixed

2022-11-17 07:40 UTC, merged