create customise links page
yalla-coop/cost-of-living-support pull request #99
Opened 2022-11-18 10:44 UTC by RamyAlshurafa

#### Issues this PR relates to
#59 

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-20 14:27 UTC, fadeomar requested changes
- [x] in first mental health link there is no number (1) https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4751%3A24551&t=dvbliRgH7hSif07C-0
![image](https://user-images.githubusercontent.com/39485495/202907556-5e80d545-f8aa-4ba6-92e5-bbb5b129c2c3.png)

  - [ ] something I'm not sure about is the link in the super admin dashboard should say "Customise resources and phone numbers" because you are adding a new route that doesn't appear in the design https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5367%3A25910&t=dvbliRgH7hSif07C-0

2022-11-20 14:27 UTC, fadeomar commented on client/src/components/Icon/icons/Refresh.js
> +      stroke-linejoin="round"
```suggestion
      strokeWidth="1.67"
      strokeLinecap="round"
      strokeLinejoin="round"
```

2022-11-20 14:27 UTC, fadeomar commented on client/src/pages/Admin/CustomiseResources/index.js
> +      </Row>
```suggestion
            <Row mt={7} style={{ flex: Number(isMobile), alignItems: 'flex-end' }}>
        {httpError && (
          <Col w={[4, 12, 12]}>
            <T.P mb={2} color="error">
              {httpError}
            </T.P>
          </Col>
        )}
        {validationErrs?.hasError?.length ? (
          <Col w={[4, 12, 12]}>
            <T.P mb="2" color="error">
              At least one of the input fields has not been filled in or details
              entered incorrectly. Please check the form above for more details.
            </T.P>
          </Col>
        ) : null}

        <Col w={[4, 6, 4]}>
          <Button
            variant="primary"
            disabled={false}
            loading={loading}
            text="Save changes"
            type="submit"
          />
        </Col>
      </Row>
```
![image](https://user-images.githubusercontent.com/39485495/202906633-b5964759-b76c-4302-a645-408ae80757f9.png)

2022-11-20 14:27 UTC, fadeomar commented on client/src/components/Icon/icons/Refresh.js
> +      stroke="#1A202B"
```suggestion
      stroke={color || "#1A202B"}
```

2022-11-20 14:27 UTC, fadeomar commented on client/src/pages/Admin/CustomiseResources/index.js
> +          <T.P isSmall color="neutralDark" mt={4} mb={6}>
```suggestion
          <T.P isSmall color="neutralDark" mb={6}>
```

2022-11-21 09:48 UTC, RamyAlshurafa commented on client/src/components/Icon/icons/Refresh.js
> +      stroke-linejoin="round"
done

2022-11-21 10:14 UTC, RamyAlshurafa commented on client/src/pages/Admin/CustomiseResources/index.js
> +      </Row>
done

2022-11-21 10:18 UTC, RamyAlshurafa commented on client/src/components/Icon/icons/Refresh.js
> +      stroke="#1A202B"
done

2022-11-21 10:22 UTC, RamyAlshurafa commented on client/src/pages/Admin/CustomiseResources/index.js
> +          <T.P isSmall color="neutralDark" mt={4} mb={6}>
done

2022-11-21 11:34 UTC, fadeomar approved these changes

2022-11-21 11:34 UTC, merged